src/Entity/Persons.php
<?php

namespace App\Entity;

use App\Repository\PersonsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonsRepository::class)]
class Persons
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'string', length: 255)]
    private $Firstname;

    #[ORM\Column(type: 'integer')]
    private $Phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $adress;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'integer')]
    private $age;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'title')]
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->Phone;
    }

    public function setPhone(int $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>My Agenda</title>
</head>
<body>
    {% block body %}
    <nav class="navbar navbar-dark bg-dark">
        <!-- Navbar content -->
        <a class="navbar-brand" href="#">My Agenda</a>
        {% if (app.user) %}
            <a class="navbar-link" href="/persons/create">Ajouter un contact</a>
        {% endif %}
    </nav>

    {% if (app.user) %}
        <span>Bonjour {{ app.user.email }}</span>
        <a href="/logout">Déconnexion</a>
    {% else %}
        <a href="/login">Connexion</a>
        <a href="/register">Inscription</a>
    {% endif %}


    <h1>Liste des contacts</h1>

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Numéro de téléphone</th>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            {% for person in tableau %}
            <tr>
                <th scope="row">{{ person.id }}</th>
                <td>{{ person.name }}</td>
                <td>{{ person.firstname }}</td>
                <td>{{ person.phone }}</td>
                <td>
                    <a href="{{path('show_person', {id: person.id}) }}" type="button" class="btn btn-info">Afficher</a>
                    {% if (app.user) %}
                        <a href="{{path('edit_person', {id: person.id}) }}" type="button" class="btn btn-warning">Modifier</a>
                        <a href="{{path('delete_person', {id: person.id}) }}" type="button" class="btn btn-danger">Supprimer</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html.twig
<div class="jumbotron">
    <h1 class="display-4">{{ person.firstname }} {{ person.name }}</h1>
    <p class="lead">{{ person.adress }} {{ person.city }}</p>
    <hr class="my-4">
    <p>Age : {{ person.age }}</p>
    <a class="btn btn-primary btn-lg" href="tel:{{ person.phone }}" role="button">Téléphoner la personne</a>
</div>

templates/edit.html.twig
{{ form(form) }}

templates/home.html.twig
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>My Agenda</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
        <!-- Navbar content -->
        <a class="navbar-brand" href="#">My Agenda</a>
    </nav>

    <h1>Liste des contacts</h1>

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Numéro de téléphone</th>
            </tr>
        </thead>
        <tbody>
            {% for person in tableau %}
            <tr>
                <td>{{ person.nom }}</td>
                <td>{{ person.prenom }}</td>
                <td>{{ person.number }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Contacts{% endblock %}

{% block content %}
<h1>Liste des contacts</h1>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Téléphone</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for contact in contacts %}
        <tr>
            <th scope="row">{{ contact.id }}</th>
            <td>{{ contact.nom }}</td>
            <td>{{ contact.prenom }}</td>
            <td>{{ contact.telephone }}</td>
            <td><a href="" type="button" class="btn btn-info">Afficher</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/list.html.twig
<nav class="navbar navbar-dark bg-dark">
    <!-- Navbar content -->
    <a class="navbar-brand" href="#">My Agenda</a>
</nav>

<h1>Liste des contacts</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Numéro de téléphone</th>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        {% for person in tableau %}
        <tr>
            <th scope="row">{{ person.id }}</th>
            <td>{{ person.name }}</td>
            <td>{{ person.firstname }}</td>
            <td>{{ person.phone }}</td>
            <td>
                <a href="{{path('show_person', {id: person.id}) }}" type="button" class="btn btn-info">Afficher</a>
                <a href="" type="button" class="btn btn-warning">Modifier</a>
                <a href="{{path('delete_person', {id: person.id}) }}" type="button" class="btn btn-danger">Supprimer</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/new.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {{ form(ProductType) }}
{% endblock %}